nodes:
  - id: product
    ref: inputs.s2-product

  - id: nir-id
    ref: resources.nir-band-name

  - id: red-id
    ref: resources.red-band-name

  - id: nir-bx
    ref: dependencies.band-extractor

  - id: red-bx
    ref: dependencies.band-extractor

  - id: ndvi
    ref: dependencies.index-calculator

  - id: plotter
    ref: models.colormap-plotter

  - id: plot
    ref: outputs.ndvi-plot

edges:
  - from:
      id: product
    to:
      id: nir-bx
      port: product
  - from:
      id: product
    to:
      id: red-bx
      port: product

  - from:
      id: nir-id
    to:
      id: nir-bx
      port: bandName
  - from:
      id: red-id
    to:
      id: red-bx
      port: bandName


  - from:
      id: nir-bx
      port: selectedBand
    to:
      id: ndvi
      port: band_a
  - from:
      id: red-bx
      port: selectedBand
    to:
      id: ndvi
      port: band_b

  - from:
      id: ndvi
      port: indexImage
    to:
      id: plotter
      port: grayscale-tiff

  - from:
      id: plotter
      port: color-plot
    to:
      id: plot
