nodes:
  - id: user
    ref: inputs.user

  - id: password
    ref: inputs.password

  - id: country_name
    ref: inputs.country_name

  - id: download_date
    ref: inputs.download_date

  - id: fire_monitor
    ref: models.fire_monitor

  - id: plot
    ref: outputs.fire-monitor-plot

edges:
  - from:
      id: user
    to:
      id: fire_monitor
      port: user

  - from:
      id: password
    to:
      id: fire_monitor
      port: password

  - from:
      id: country_name
    to:
      id: fire_monitor
      port: country_name

  - from:
      id: download_date
    to:
      id: fire_monitor
      port: download_date

  - from:
      id: fire_monitor
      port: fire-monitor-plot
    to:
      id: plot
