nodes:
  - id: user
    ref: inputs.user

  - id: password
    ref: inputs.password

  - id: fire-risk-plotter
    ref: models.fire-risk-plotter

  - id: plot
    ref: outputs.firerisk-plot
  
edges:

  - from:
      id: user
    to:
      id: fire-risk-plotter
      port: user

  - from:
      id: password
    to:
      id: fire-risk-plotter
      port: password

  - from:
      id: fire-risk-plotter
      port: firerisk-plot
    to:
      id: plot
